name: SpaceTweet web server
description: Serves the web UI of SpaceTweet

setup: npm install
startup:
  command: node_modules/.bin/lsc servers/cli.ls --name {{name}} --exorelay-port {{exorelay-port}} --exocom-port {{exocom-port}}
  online-text: all systems go


messages:
  sends:
    - user.get-details
    - user.update
    - users.list
    - users.create
    - tweets.list
    - tweets.create
  receives:
    - user.details
    - user.not-found
    - user.updated
    - users.listed
    - users.created
    - tweets.listed
    - tweets.created
