name: SpaceTweet web server
description: Serves the web UI of SpaceTweet

setup: npm install
startup:
  command: node_modules/.bin/lsc servers/cli.ls --name {{name}} --exorelay-port {{exorelay-port}} --exocomm-port {{exocomm-port}}
  online-text: all systems go


messages:
  sends:
    - users.list
    - users.create
  receives:
    - users.listed
    - users.created
