type: space-tweet-web-service
description: Serves the web UI of SpaceTweet
author: originate


startup:
  command: node_modules/.bin/lsc app
  online-text: all systems go


messages:
  sends:
    - get user details
    - delete user
    - update user
    - list users
    - create user
    - list tweets
    - create tweet
    - delete tweet
  receives:
    - user details
    - user not found
    - user updated
    - user deleted
    - users listed
    - user created
    - tweets listed
    - tweet created
    - tweet deleted


docker:
  ports:
    - '3000:3000'

environment:
  default:
  development:
  production:
  secrets:

production:
  url: spacetweet.originate.com
  cpu: 128
  memory: 128
  public-port: 3000
  health-check: '/'
