type: space-tweet-web-service
description: Serves the web UI of SpaceTweet
author: originate

setup: yarn
startup:
  command: node_modules/.bin/lsc app
  online-text: all systems go


messages:
  sends:
    - user.get-details
    - user.delete
    - user.update
    - users.list
    - users.create
    - tweets.list
    - tweets.create
    - tweets.delete
  receives:
    - user.details
    - user.not-found
    - user.updated
    - user.deleted
    - users.listed
    - users.created
    - tweets.listed
    - tweets.created
    - tweets.deleted


docker:
  publish:
    - '3000:3000'


production:
  url: exosphere-staging.originate.com
  aws:
    cpu: 100
    memory: 500
    essential: true
    public-port: 3000
