type: public
description: Serves the web UI of SpaceTweet
author: originate


startup:
  online-text: all systems go


dependency-data:
  exocom:
    sends:
      - get user details
      - delete user
      - update user
      - list users
      - create user
      - list tweets
      - create tweet
      - delete tweet
    receives:
      - user details
      - user not found
      - user updated
      - user deleted
      - users listed
      - user created
      - tweets listed
      - tweet created
      - tweet deleted

development:
  port: 3000
  scripts:
    run: node_modules/.bin/lsc app

production:
  port: 3000
  health-check: '/'

remote:
  cpu: 128
  memory: 128
  environments:
    production:
      url: spacetweet.originate.com
