version: '3'
services:
  exocom0.21.8:
    image: 'originate/exocom:0.21.8'
    command: bin/exocom
    container_name: exocom0.21.8
    environment:
      ROLE: exocom
      PORT: $EXOCOM_PORT
      SERVICE_ROUTES: >-
        [{"role":"space-tweet-web-service","receives":["user.details","user.not-found","user.updated","user.deleted","users.listed","users.created","tweets.listed","tweets.created","tweets.deleted"],"sends":["user.get-details","user.delete","user.update","users.list","users.create","tweets.list","tweets.create","tweets.delete"]},{"role":"exosphere-users-service","receives":["users.create","users.list","user.get-details","user.update","user.delete"],"sends":["users.created","users.listed","user.details","user.not-found","user.updated","user.deleted","users.not-created"]},{"role":"exosphere-tweets-service","receives":["tweets.create","tweets.list","tweets.get-details","tweets.update","tweets.delete"],"sends":["tweets.created","tweets.listed","tweets.details","tweets.not-found","tweets.updated","tweets.deleted","tweets.not-created"]}]
  space-tweet-web-service:
    build: ../web-server
    container_name: space-tweet-web-service
    command: node_modules/.bin/lsc app
    ports:
      - '3000:3000'
    environment:
      ROLE: space-tweet-web-service
      EXOCOM_HOST: exocom0.21.8
      EXOCOM_PORT: $EXOCOM_PORT
    depends_on:
      - exocom0.21.8
  exosphere-users-service:
    build: ../users-service
    container_name: exosphere-users-service
    command: node_modules/exoservice/bin/exo-js
    links:
      - 'mongo3.4.0:mongo'
    environment:
      ROLE: exosphere-users-service
      EXOCOM_HOST: exocom0.21.8
      EXOCOM_PORT: $EXOCOM_PORT
      MONGO: mongo
    depends_on:
      - exocom0.21.8
      - mongo3.4.0
  mongo3.4.0:
    image: 'mongo:3.4.0'
    container_name: mongo3.4.0
    ports:
      - '27017:27017'
    volumes:
      - '/Users/hugoho/.exosphere/SpaceTweet/mongo/data:/data/db'
  exosphere-tweets-service:
    build: ../tweets-service
    container_name: exosphere-tweets-service
    command: node_modules/exoservice/bin/exo-js
    links:
      - 'mongo3.4.0:mongo'
    environment:
      ROLE: exosphere-tweets-service
      EXOCOM_HOST: exocom0.21.8
      EXOCOM_PORT: $EXOCOM_PORT
      MONGO: mongo
    depends_on:
      - exocom0.21.8
      - mongo3.4.0
