name: SpaceTweet
description: an example for an ExoSphere application
version: 0.0.1

bus:
  type: exocom
  version: 0.21.8

environments:
  local:
  production:
    domain: spacetweet.originate.com
    providers:
      aws:
        region: us-west-2
        public-cluster-size: t2.medium
        private-cluster-size: t2.nano
        remote-state-store: terraform.state.prod
  staging:
    url: dev.megabyt.es
    provider: aws
    region: us-west-2

services:
  public:
    space-tweet-web-service:
      location: ./web-server
      docker_image: originate/space-tweet-web-service
  private:
    exosphere-users-service:
      location: ./users-service
      docker_image: originate/exosphere-users-service
    exosphere-tweets-service:
      location: ./tweets-service
      docker_image: originate/exosphere-tweets-service
