name: space-tweet
description: an example for an ExoSphere application
version: 0.0.1

dependencies:
  - name: exocom
    version: 0.24.0
  # - name: mongo
  #   version: 3.4.0
  #   config:
  #     ports:
  #       - '4000:4000'
  #     volumes:
  #       - '{{EXO_DATA_PATH}}:/data/db'
  #     online-text: 'waiting for connections'
  #     dependency-environment:
  #       DB_NAME: 'test-db'
  #     service-environment:
  #       COLLECTION_NAME: 'test-collection'


production:
  url: spacetweet.originate.com

services:
  public:
    space-tweet-web-service:
      location: ./web-server
  private:
    exosphere-users-service:
      location: ./users-service
    exosphere-tweets-service:
      location: ./tweets-service
