name: space-tweet

local:
  dependencies:
    exocom:
      image: originate/exocom:0.27.0
    mongo:
      image: mongo:3.4.0
      persist:
        - '/data/db'
      environment-variables:
        DB_NAME: 'test-db'

remote:
  dependencies:
    exocom:
      type: exocom
      template-config:
        version: 0.27.0
  environments:
    production:
      url: spacetweet.originate.com
      region: us-west-2
      account-id: 653673351586
      ssl-certificate-arn: 	arn:aws:acm:us-west-2:653673351586:certificate/744b5913-9a40-4bc4-94b6-cc9adf8f7e96
      environment-variables:
        EXOCOM_HOST: exocom.production-space-tweet.local

services:
  space-tweet-web-service:
    location: ./web-server
  storage-service:
    location: ./storage-service
