name: space-tweet

local:
  dependencies:
    exocom:
      image: originate/exocom:0.27.0
    mongo:
      image: mongo:3.4.0
      persist:
        - '/data/db'
      environment-variables:
        DB_NAME: 'test-db'

remote:
  dependencies:
    exocom:
      type: exocom
      template-config:
        version: 0.27.0
  environments:
    production:
      url: spacetweet.originate.com
      region: us-west-2
      account-id: 518695917306
      ssl-certificate-arn: arn:aws:acm:us-west-2:518695917306:certificate/c9a6be72-c6a3-4551-8e5b-53f5cfd89199
      environment-variables:
        EXOCOM_HOST: exocom.space-tweet.local

services:
  space-tweet-web-service:
    location: ./web-server
  storage-service:
    location: ./storage-service
