name: spacetweet

local:
  dependencies:
    exocom:
      image: originate/exocom:0.27.0
    mongo:
      image: mongo:3.4.0
      persist:
        - '/data/db'
      environment-variables:
        DB_NAME: 'test-db'

remote:
  dependencies:
    exocom:
      type: exocom
      template-config:
        version: 0.27.0
  environments:
    production:
      url: spacetweet.originate.com
      region: us-west-2
      account-id: 518695917306
      ssl-certificate-arn: 	arn:aws:acm:us-east-2:518695917306:certificate/b613b539-e673-41bc-9c4c-bb27cfcc2195
      environment-variables:
        EXOCOM_HOST: exocom.production-space-tweet.local

services:
  space-tweet-web-service:
    location: ./web-server
  storage-service:
    location: ./storage-service
