name: space-tweet
description: an example for an ExoSphere application
version: 0.0.1

dependencies:
  - name: exocom
    version: 0.21.8

production:
  url: spacetweet.originate.com

services:
  public:
    space-tweet-web-service:
      location: ./web-server
      docker_image: originate/space-tweet-web-service
  private:
    exosphere-users-service:
      location: ./users-service
      docker_image: originate/exosphere-users-service
    exosphere-tweets-service:
      location: ./tweets-service
      docker_image: originate/exosphere-tweets-service
