SHARED:
  &installExosphereStep
  run:
    name: install exosphere
    command: |
      curl --output exo --location --fail https://github.com/Originate/exosphere/releases/download/v0.36.1/exo-linux-amd64
      chmod +x exo
      sudo mv exo /usr/local/bin/

version: 2
jobs:
  test:
    working_directory: ~/space-tweet
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - *installExosphereStep
      - run:
          name: run tests
          command: exo test
  deploy:
    working_directory: ~/space-tweet
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - setup_remote_docker
      - *installExosphereStep
      - run:
          name: install terraform
          command: |
            curl https://releases.hashicorp.com/terraform/0.11.0/terraform_0.11.0_linux_amd64.zip > terraform_0.11.0_linux_amd64.zip
            sudo unzip terraform_0.11.0_linux_amd64.zip -d /usr/local/bin
            rm terraform_0.11.0_linux_amd64.zip
      - run:
          name: deploy updates
          command: exo deploy production --auto-approve

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
