version: "3"
services:
  exocom:
    image: originate/exocom:0.27.0
    environment:
      SERVICE_DATA: '{"space-tweet-web-service":{"receives":["user details","user
        not found","user updated","user deleted","users listed","user created","tweets
        listed","tweet created","tweet deleted"],"sends":["get user details","delete
        user","update user","list users","create user","list tweets","create tweet","delete
        tweet"]},"storage-service":{"receives":["create tweet","create user","delete
        tweet","delete user","get tweet details","get user details","list tweets","list
        users","update tweet","update user"],"sends":["tweet created","tweet deleted","tweet
        details","tweet not created","tweet not found","tweet updated","tweets listed","user
        created","user deleted","user details","user not created","user not found","user
        updated","users listed"]}}'
    restart: on-failure
  mongo:
    image: mongo:3.4.0
    volumes:
    - mongo__data_db:/data/db
    environment:
      DB_NAME: test-db
      SERVICE_DATA: '{"space-tweet-web-service":{},"storage-service":{}}'
    restart: on-failure
  space-tweet-web-service:
    build:
      context: ${APP_PATH}/web-server
      dockerfile: Dockerfile.dev
    command: lsc app
    ports:
    - 3000:3000
    volumes:
    - ${APP_PATH}/web-server:/mnt
    environment:
      EXOCOM_HOST: exocom
      MONGO_HOST: mongo
      ROLE: space-tweet-web-service
    depends_on:
    - exocom
    - mongo
    restart: on-failure
  storage-service:
    build:
      context: ${APP_PATH}/storage-service
      dockerfile: Dockerfile.dev
    command: node src/server.js
    volumes:
    - ${APP_PATH}/storage-service:/mnt
    environment:
      EXOCOM_HOST: exocom
      MONGO_HOST: mongo
      ROLE: storage-service
      SPACE_TWEET_WEB_SERVICE_EXTERNAL_ORIGIN: http://localhost:3000
      SPACE_TWEET_WEB_SERVICE_INTERNAL_ORIGIN: http://space-tweet-web-service:3000
    depends_on:
    - exocom
    - mongo
    restart: on-failure
volumes:
  mongo__data_db: null
