version: "3"
services:
  exocom0.26.3:
    image: originate/exocom:0.26.3
    container_name: exocom0.26.3
    environment:
      ROLE: exocom
      SERVICE_ROUTES: '[{"receives":["create tweet","list tweets","get tweet details","update
        tweet","delete tweet"],"role":"exosphere-tweets-service","sends":["tweet created","tweets
        listed","tweet details","tweet not found","tweet updated","tweet deleted","tweet
        not created"]},{"receives":["create user","list users","get user details","update
        user","delete user"],"role":"exosphere-users-service","sends":["user created","users
        listed","user details","user not found","user updated","user deleted","user
        not created"]},{"receives":["user details","user not found","user updated","user
        deleted","users listed","user created","tweets listed","tweet created","tweet
        deleted"],"role":"space-tweet-web-service","sends":["get user details","delete
        user","update user","list users","create user","list tweets","create tweet","delete
        tweet"]}]'
    restart: on-failure
  exosphere-tweets-service:
    build:
      context: ${APP_PATH}/tweets-service
      dockerfile: Dockerfile.prod
    container_name: exosphere-tweets-service
    environment:
      COLLECTION_NAME: test-collection
      EXOCOM_HOST: exocom0.26.3
      MONGO: mongo3.4.0
      MONGODB_PW: ""
      MONGODB_USER: ""
      ROLE: exosphere-tweets-service
    depends_on:
    - exocom0.26.3
    - mongo3.4.0
    - mongo3.4.0
    restart: on-failure
  exosphere-users-service:
    build:
      context: ${APP_PATH}/users-service
      dockerfile: Dockerfile.prod
    container_name: exosphere-users-service
    environment:
      COLLECTION_NAME: test-collection
      EXOCOM_HOST: exocom0.26.3
      MONGO: mongo3.4.0
      MONGODB_PW: ""
      MONGODB_USER: ""
      ROLE: exosphere-users-service
    depends_on:
    - exocom0.26.3
    - mongo3.4.0
    - mongo3.4.0
    restart: on-failure
  mongo3.4.0:
    image: mongo:3.4.0
    container_name: mongo3.4.0
    ports:
    - 4000:4000
    volumes:
    - ${APP_PATH}/.exosphere/data/mongo:/data/db
    environment:
      DB_NAME: test-db
    restart: on-failure
  space-tweet-web-service:
    build:
      context: ${APP_PATH}/web-server
      dockerfile: Dockerfile.prod
    container_name: space-tweet-web-service
    ports:
    - 3000:3000
    environment:
      COLLECTION_NAME: test-collection
      EXOCOM_HOST: exocom0.26.3
      MONGO: mongo3.4.0
      ROLE: space-tweet-web-service
    depends_on:
    - exocom0.26.3
    - mongo3.4.0
    restart: on-failure
