type: worker

dependency-data:
  exocom:
    receives:
      - create tweet
      - create user
      - delete tweet
      - delete user
      - get tweet details
      - get user details
      - list tweets
      - list users
      - update tweet
      - update user
    sends:
      - tweet created
      - tweet deleted
      - tweet details
      - tweet not created
      - tweet not found
      - tweet updated
      - tweets listed
      - user created
      - user deleted
      - user details
      - user not created
      - user not found
      - user updated
      - users listed

development:
  scripts:
    run: node src/server.js
    test: /node_modules/.bin/cucumber-js --fail-fast

remote:
  cpu: 100
  memory: 500
  secrets:
    - MONGODB_USER
    - MONGODB_PW
