FROM nodesource/node

# These steps ensure that npm install is only run when package.json changes
COPY ./package.json .
RUN npm install -g LiveScript
RUN npm install --production
COPY . .

CMD ["lsc", "src/server.ls"]
