type: exosphere-tweets-service
description: Generic MongoDB storage service
author: originate

setup: yarn
startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/.bin/cucumber-js


messages:
  receives:
    - tweets.create
    - tweets.list
    - tweets.get-details
    - tweets.update
    - tweets.delete
  sends:
    - tweets.created
    - tweets.listed
    - tweets.details
    - tweets.not-found
    - tweets.updated
    - tweets.deleted
    - tweets.not-created

dependencies:
  mongo:
    dev:
      image: 'mongo'
      version: '3.4.0'
      volumes:
        - '{{EXO_DATA_PATH}}:/data/db'
      ports:
        - '27017:27017'
      online-text: 'waiting for connections'
    prod: 'ds143608.mlab.com:43608'


production:
  aws:
    cpu: 100
    memory: 500
    essential: true
