type: exosphere-tweets-service
description: Generic MongoDB storage service
author: originate


startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/.bin/cucumber-js


messages:
  receives:
    - create tweet
    - list tweets
    - get tweet details
    - update tweet
    - delete tweet
  sends:
    - tweet created
    - tweets listed
    - tweet details
    - tweet not found
    - tweet updated
    - tweet deleted
    - tweet not created

environment:
  default:
  development:
  production:
    ROLE: exosphere-tweets-service
    EXOCOM_PORT: 80
    EXOCOM_HOST: exocom.space-tweet.local
  secrets:
    - MONGODB_USER
    - MONGODB_PW


production:
  cpu: 100
  memory: 500

# dependencies:
#   - name: mongo
#     version: 3.4.0
