type: exosphere-tweets-service
description: Generic MongoDB storage service
author: originate


startup:
  command: node_modules/exoservice/bin/exo-js
  online-text: online at port
tests: node_modules/.bin/cucumber-js


messages:
  receives:
    - create tweet
    - list tweets
    - get tweet details
    - update tweet
    - delete tweet
  sends:
    - tweet created
    - tweets listed
    - tweet details
    - tweet not found
    - tweet updated
    - tweet deleted
    - tweet not created


# dependencies:
#   - name: mongo
#     version: 3.4.0

user-data:
  mongo:
    production-endpoint: 'ds143608.mlab.com:43608'

production:
  cpu: 128
  memory: 128
