type: worker
description: Generic MongoDB storage service
author: originate

dependency-data:
  exocom:
    receives:
      - create tweet
      - list tweets
      - get tweet details
      - update tweet
      - delete tweet
    sends:
      - tweet created
      - tweets listed
      - tweet details
      - tweet not found
      - tweet updated
      - tweet deleted
      - tweet not created

development:
  scripts:
    run: lsc src/server.ls
    test: /node_modules/.bin/cucumber-js

local:
  secrets:
    - MONGODB_USER
    - MONGODB_PW

remote:
  cpu: 100
  memory: 500
  secrets:
    - MONGODB_USER
    - MONGODB_PW
